=begin
#Miami Open 211 API

#This is a developer area for the Miami Open211 API, providing access to the raw data behind the Switchboard of Miami website. The purpose of this API is to allow anyone to develop web, mobile, or other types of applications that serve the mission of Miami Open211.

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require "uri"

module SwaggerClient
  class SearchApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # Search
    # This endpoint retrieves all locations that match the criteria based on the parameters below. Multiple parameters can be used at the same time, separated by an ampersand (&).
    # @param accept 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :category 
    # @option opts [String] :email 
    # @option opts [String] :keyword 
    # @option opts [String] :language 
    # @option opts [String] :lat_lng 
    # @option opts [String] :location 
    # @option opts [String] :org_name 
    # @option opts [String] :radius 
    # @option opts [String] :service_area 
    # @option opts [String] :status 
    # @option opts [String] :page 
    # @option opts [String] :per_page 
    # @return [Array<Location>]
    def search_locations(accept, opts = {})
      data, _status_code, _headers = search_locations_with_http_info(accept, opts)
      return data
    end

    # Search
    # This endpoint retrieves all locations that match the criteria based on the parameters below. Multiple parameters can be used at the same time, separated by an ampersand (&amp;).
    # @param accept 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :category 
    # @option opts [String] :email 
    # @option opts [String] :keyword 
    # @option opts [String] :language 
    # @option opts [String] :lat_lng 
    # @option opts [String] :location 
    # @option opts [String] :org_name 
    # @option opts [String] :radius 
    # @option opts [String] :service_area 
    # @option opts [String] :status 
    # @option opts [String] :page 
    # @option opts [String] :per_page 
    # @return [Array<(Array<Location>, Fixnum, Hash)>] Array<Location> data, response status code and response headers
    def search_locations_with_http_info(accept, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: SearchApi.search_locations ..."
      end
      # verify the required parameter 'accept' is set
      fail ArgumentError, "Missing the required parameter 'accept' when calling SearchApi.search_locations" if accept.nil?
      # resource path
      local_var_path = "/search".sub('{format}','json')

      # query parameters
      query_params = {}
      query_params[:'category'] = opts[:'category'] if !opts[:'category'].nil?
      query_params[:'email'] = opts[:'email'] if !opts[:'email'].nil?
      query_params[:'keyword'] = opts[:'keyword'] if !opts[:'keyword'].nil?
      query_params[:'language'] = opts[:'language'] if !opts[:'language'].nil?
      query_params[:'lat_lng'] = opts[:'lat_lng'] if !opts[:'lat_lng'].nil?
      query_params[:'location'] = opts[:'location'] if !opts[:'location'].nil?
      query_params[:'org_name'] = opts[:'org_name'] if !opts[:'org_name'].nil?
      query_params[:'radius'] = opts[:'radius'] if !opts[:'radius'].nil?
      query_params[:'service_area'] = opts[:'service_area'] if !opts[:'service_area'].nil?
      query_params[:'status'] = opts[:'status'] if !opts[:'status'].nil?
      query_params[:'page'] = opts[:'page'] if !opts[:'page'].nil?
      query_params[:'per_page'] = opts[:'per_page'] if !opts[:'per_page'].nil?

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = []
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)
      header_params[:'Accept'] = accept

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<Location>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SearchApi#search_locations\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
