//
// Location.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Location: JSONEncodable {
    /** Each location must have a unique identifier */
    public var id: String?
    /** Each location must belong to a single organization. The identifier of the organization should be given here. */
    public var organizationId: String?
    /** The name of the location */
    public var name: String?
    /** An alternative name for the location */
    public var alternateName: String?
    /** A description of this location. */
    public var description: String?
    /** A description of the access to public or private transportation to and from the location. */
    public var transportation: String?
    /** Y coordinate of location expressed in decimal degrees in WGS84 datum. */
    public var latitude: String?
    /** X coordinate of location expressed in decimal degrees in WGS84 datum. */
    public var longitude: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["organization_id"] = self.organizationId
        nillableDictionary["name"] = self.name
        nillableDictionary["alternate_name"] = self.alternateName
        nillableDictionary["description"] = self.description
        nillableDictionary["transportation"] = self.transportation
        nillableDictionary["latitude"] = self.latitude
        nillableDictionary["longitude"] = self.longitude
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
