=begin
#Miami Open 211 API

#This is a developer area for the Miami Open211 API, providing access to the raw data behind the Switchboard of Miami website. The purpose of this API is to allow anyone to develop web, mobile, or other types of applications that serve the mission of Miami Open211.

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::SearchApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SearchApi' do
  before do
    # run before each test
    @instance = SwaggerClient::SearchApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SearchApi' do
    it 'should create an instact of SearchApi' do
      expect(@instance).to be_instance_of(SwaggerClient::SearchApi)
    end
  end

  # unit tests for search_locations
  # Search
  # This endpoint retrieves all locations that match the criteria based on the parameters below. Multiple parameters can be used at the same time, separated by an ampersand (&amp;).
  # @param accept 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :category 
  # @option opts [String] :email 
  # @option opts [String] :keyword 
  # @option opts [String] :language 
  # @option opts [String] :lat_lng 
  # @option opts [String] :location 
  # @option opts [String] :org_name 
  # @option opts [String] :radius 
  # @option opts [String] :service_area 
  # @option opts [String] :status 
  # @option opts [String] :page 
  # @option opts [String] :per_page 
  # @return [Array<Location>]
  describe 'search_locations test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
