/**
 * Miami Open 211 API
 * This is a developer area for the Miami Open211 API, providing access to the raw data behind the Switchboard of Miami website. The purpose of this API is to allow anyone to develop web, mobile, or other types of applications that serve the mission of Miami Open211.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class Phone  {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("location_id")
  private String locationId = null;
  @SerializedName("service_id")
  private String serviceId = null;
  @SerializedName("organization_id")
  private String organizationId = null;
  @SerializedName("contact_id")
  private String contactId = null;
  @SerializedName("number")
  private String number = null;
  @SerializedName("extension")
  private String extension = null;
  @SerializedName("type")
  private String type = null;
  @SerializedName("department")
  private String department = null;

  /**
   * Each entry must have a unique identifier
   **/
  @ApiModelProperty(value = "Each entry must have a unique identifier")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   * The identifier of the location where this phone number is located
   **/
  @ApiModelProperty(value = "The identifier of the location where this phone number is located")
  public String getLocationId() {
    return locationId;
  }
  public void setLocationId(String locationId) {
    this.locationId = locationId;
  }

  /**
   * The identifier of the service for which this is the phone number
   **/
  @ApiModelProperty(value = "The identifier of the service for which this is the phone number")
  public String getServiceId() {
    return serviceId;
  }
  public void setServiceId(String serviceId) {
    this.serviceId = serviceId;
  }

  /**
   * The identifier of the organisation for which this is the phone number
   **/
  @ApiModelProperty(value = "The identifier of the organisation for which this is the phone number")
  public String getOrganizationId() {
    return organizationId;
  }
  public void setOrganizationId(String organizationId) {
    this.organizationId = organizationId;
  }

  /**
   * The identifier of the contact for which this is the phone number
   **/
  @ApiModelProperty(value = "The identifier of the contact for which this is the phone number")
  public String getContactId() {
    return contactId;
  }
  public void setContactId(String contactId) {
    this.contactId = contactId;
  }

  /**
   * The phone number
   **/
  @ApiModelProperty(value = "The phone number")
  public String getNumber() {
    return number;
  }
  public void setNumber(String number) {
    this.number = number;
  }

  /**
   * The extension of the phone number
   **/
  @ApiModelProperty(value = "The extension of the phone number")
  public String getExtension() {
    return extension;
  }
  public void setExtension(String extension) {
    this.extension = extension;
  }

  /**
   * Whether the phone number relates to a fixed or cellular phone
   **/
  @ApiModelProperty(value = "Whether the phone number relates to a fixed or cellular phone")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  /**
   * The department for which this is the phone number
   **/
  @ApiModelProperty(value = "The department for which this is the phone number")
  public String getDepartment() {
    return department;
  }
  public void setDepartment(String department) {
    this.department = department;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Phone phone = (Phone) o;
    return (id == null ? phone.id == null : id.equals(phone.id)) &&
        (locationId == null ? phone.locationId == null : locationId.equals(phone.locationId)) &&
        (serviceId == null ? phone.serviceId == null : serviceId.equals(phone.serviceId)) &&
        (organizationId == null ? phone.organizationId == null : organizationId.equals(phone.organizationId)) &&
        (contactId == null ? phone.contactId == null : contactId.equals(phone.contactId)) &&
        (number == null ? phone.number == null : number.equals(phone.number)) &&
        (extension == null ? phone.extension == null : extension.equals(phone.extension)) &&
        (type == null ? phone.type == null : type.equals(phone.type)) &&
        (department == null ? phone.department == null : department.equals(phone.department));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (id == null ? 0: id.hashCode());
    result = 31 * result + (locationId == null ? 0: locationId.hashCode());
    result = 31 * result + (serviceId == null ? 0: serviceId.hashCode());
    result = 31 * result + (organizationId == null ? 0: organizationId.hashCode());
    result = 31 * result + (contactId == null ? 0: contactId.hashCode());
    result = 31 * result + (number == null ? 0: number.hashCode());
    result = 31 * result + (extension == null ? 0: extension.hashCode());
    result = 31 * result + (type == null ? 0: type.hashCode());
    result = 31 * result + (department == null ? 0: department.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Phone {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  locationId: ").append(locationId).append("\n");
    sb.append("  serviceId: ").append(serviceId).append("\n");
    sb.append("  organizationId: ").append(organizationId).append("\n");
    sb.append("  contactId: ").append(contactId).append("\n");
    sb.append("  number: ").append(number).append("\n");
    sb.append("  extension: ").append(extension).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  department: ").append(department).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
