#import <Foundation/Foundation.h>
#import "SWGLocation.h"
#import "SWGApi.h"

/**
* Miami Open 211 API
* This is a developer area for the Miami Open211 API, providing access to the raw data behind the Switchboard of Miami website. The purpose of this API is to allow anyone to develop web, mobile, or other types of applications that serve the mission of Miami Open211.
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SWGSearchApi: NSObject <SWGApi>

extern NSString* kSWGSearchApiErrorDomain;
extern NSInteger kSWGSearchApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Search
/// This endpoint retrieves all locations that match the criteria based on the parameters below. Multiple parameters can be used at the same time, separated by an ampersand (&).
///
/// @param accept  (default to application/vnd.ohanapi+json; version=1)
/// @param category  (optional)
/// @param email  (optional)
/// @param keyword  (optional)
/// @param language  (optional)
/// @param latLng  (optional)
/// @param location  (optional)
/// @param orgName  (optional)
/// @param radius  (optional)
/// @param serviceArea  (optional)
/// @param status  (optional)
/// @param page  (optional)
/// @param perPage  (optional)
/// 
///  code:200 message:"Successful response"
///
/// @return NSArray<SWGLocation>*
-(NSNumber*) searchLocationsWithAccept: (NSString*) accept
    category: (NSString*) category
    email: (NSString*) email
    keyword: (NSString*) keyword
    language: (NSString*) language
    latLng: (NSString*) latLng
    location: (NSString*) location
    orgName: (NSString*) orgName
    radius: (NSString*) radius
    serviceArea: (NSString*) serviceArea
    status: (NSString*) status
    page: (NSString*) page
    perPage: (NSString*) perPage
    completionHandler: (void (^)(NSArray<SWGLocation>* output, NSError* error)) handler;



@end
